version: "3.8"
services:
  mc:
    image: ${IMAGE:-itzg/minecraft-server}
    container_name: ${NAME:-delMe}
    env_file:
      - ./config/mc1.env
    ports:
      - "${PORT:-25565}:25565"
      - "${RCON:-25575}:25575"
    volumes:
      - /mnt/nasworld/${RACK:-dev}/${NAME:-delMe}:/data
    stdin_open: true
    tty: true
    restart: unless-stopped
volumes:
  data: {}